language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
script:
  - pytest --cov=edutorch --cov-report= --durations=0
after_success:
  - codecov
